# Generated by Django 5.2.7 on 2025-10-11 11:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('remote', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('expired', 'Expired')], default='on site', max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('temporary', 'Temporary'), ('internship', 'Internship'), ('remote', 'Remote')], max_length=20)),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Entry Level'), ('mid', 'Mid Level'), ('senior', 'Senior Level'), ('executive', 'Executive'), ('student', 'Student')], max_length=20)),
                ('duration', models.CharField(blank=True, help_text='e.g., Full-time, 12 months, etc.', max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('passport_number', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('id_card', models.CharField(max_length=100)),
                ('card_image', models.JSONField(default=list, help_text='upload front and back of the id card')),
                ('date_of_birth', models.DateField(blank=True, help_text="Applicant's date of birth.", null=True)),
                ('profile_photo', models.ImageField(blank=True, help_text='Optional profile photo of the applicant.', null=True, upload_to='')),
                ('bio', models.TextField(blank=True, help_text='Brief summary or professional bio.', null=True)),
                ('linkedin_profile', models.URLField(blank=True, help_text="Link to applicant's LinkedIn profile.", null=True)),
                ('website_or_portfolio', models.URLField(blank=True, help_text='Link to personal website or professional portfolio.', null=True)),
                ('languages_spoken', models.CharField(blank=True, help_text='Languages spoken fluently (comma-separated).', max_length=255, null=True)),
                ('education', models.TextField(blank=True, help_text='Education background or degrees obtained.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('interview_type', models.CharField(choices=[('video', 'Video Interview'), ('phone', 'Phone Interview'), ('in_person', 'In-Person Interview')], default='video', max_length=20)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='travel.applicant')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='travel.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('resume', models.FileField(upload_to='')),
                ('certification', models.FileField(blank=True, null=True, upload_to='')),
                ('cover_letter', models.TextField(blank=True, help_text='Optional cover letter explaining motivation or suitability.', null=True)),
                ('available_start_date', models.DateField(blank=True, help_text='When the applicant is available to start.', null=True)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('INTERVIEW', 'Interview Stage'), ('OFFERED', 'Offered'), ('REJECTED', 'Rejected'), ('WITHDRAWN', 'Withdrawn')], default='SUBMITTED', help_text='Current status of the application process.', max_length=20)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.applicant')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CampaignImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('canpaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='travel.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.category'),
        ),
        migrations.CreateModel(
            name='RequirementBenefit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('short_description', models.TextField(max_length=500)),
                ('full_description', models.TextField()),
                ('requirements', models.JSONField(default=list, help_text='List of requirements as JSON')),
                ('responsibilities', models.JSONField(blank=True, default=list, help_text='List of responsibilities as JSON')),
                ('preferred_qualifications', models.JSONField(blank=True, default=list, help_text='Preferred qualifications as JSON')),
                ('benefit', models.JSONField(blank=True, default=list, null=True)),
                ('compagin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_benefits', to='travel.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
