# Generated by Django 5.2.7 on 2025-10-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='application_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
