# Generated by Django 5.2.7 on 2025-10-16 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_application_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='qualification',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
