# Generated by Django 5.2.7 on 2025-10-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_application_qualification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='card_image',
        ),
        migrations.AddField(
            model_name='applicant',
            name='card_image_back',
            field=models.ImageField(default=list, help_text='upload back of the id card', upload_to=''),
        ),
        migrations.AddField(
            model_name='applicant',
            name='card_image_front',
            field=models.ImageField(default=list, help_text='upload front of the id card', upload_to=''),
        ),
        migrations.AddField(
            model_name='applicant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
