# Generated by Django 5.2.7 on 2025-10-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_availableslot_alter_application_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookedinterview',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
