# Generated by Django 5.2.7 on 2025-10-17 10:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_bookedinterview_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='whats_app',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('currency', models.CharField(choices=[('$', '$'), ('£', '£'), ('₵', '₵')], max_length=100)),
                ('charged_currency', models.CharField(choices=[('$', '$'), ('£', '£'), ('₵', '₵')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('charged_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], max_length=100)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.applicant')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.campaign')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
