# Generated by Django 5.2.7 on 2025-10-18 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0010_rate_alter_bookedinterview_slot'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookedinterview',
            options={},
        ),
        migrations.AlterField(
            model_name='bookedinterview',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookedinterview',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='travel.availableslot'),
        ),
        migrations.AddConstraint(
            model_name='bookedinterview',
            constraint=models.UniqueConstraint(fields=('slot',), name='unique_booking_per_slot'),
        ),
    ]
