# Generated by Django 5.2.7 on 2025-10-18 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0011_alter_bookedinterview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedinterview',
            name='applicant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booked_interviews', to='travel.applicant'),
        ),
    ]
