# Generated by Django 5.2.7 on 2025-10-18 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0012_alter_bookedinterview_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
