# Generated by Django 5.2.7 on 2025-10-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0013_alter_application_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.FileField(blank=True, help_text='Optional cover letter explaining motivation or suitability.', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='application',
            name='qualification',
            field=models.TextField(blank=True, help_text='enter any skill you have ', null=True),
        ),
    ]
